# Generated by Django 3.1 on 2020-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_auto_20200812_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='code_ar',
            field=models.CharField(max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='code_en',
            field=models.CharField(max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='title_ar',
            field=models.CharField(max_length=180, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='title_en',
            field=models.CharField(max_length=180, null=True, verbose_name='Title'),
        ),
    ]
